// Danh sách country code cho đăng ký/đăng nhập Tuya — lấy NGUYÊN bảng
// "Western Europe Data Center" (app SDK post-2025-11-25 route các nước này về Western Europe):
// https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb#title-6
// Lưu ý: DC của account do NGÀY TẠO appKey + bảng mapping này quyết (không đổi được từ client).
export type Country = { code: string; name: string };

export const DEFAULT_COUNTRY_CODE = '49'; // Germany — khớp account/dữ liệu hiện có

export const COUNTRIES: Country[] = [
  { code: '7', name: 'Russia' },
  { code: '20', name: 'Egypt' },
  { code: '27', name: 'South Africa' },
  { code: '30', name: 'Greece' },
  { code: '31', name: 'Netherlands' },
  { code: '32', name: 'Belgium' },
  { code: '33', name: 'France' },
  { code: '34', name: 'Spain' },
  { code: '36', name: 'Hungary' },
  { code: '39', name: 'Italy' },
  { code: '40', name: 'Romania' },
  { code: '41', name: 'Switzerland' },
  { code: '43', name: 'Austria' },
  { code: '44', name: 'United Kingdom' },
  { code: '45', name: 'Denmark' },
  { code: '46', name: 'Sweden' },
  { code: '47', name: 'Norway' },
  { code: '48', name: 'Poland' },
  { code: '49', name: 'Germany' },
  { code: '61', name: 'Australia' },
  { code: '90', name: 'Turkey' },
  { code: '92', name: 'Pakistan' },
  { code: '93', name: 'Afghanistan' },
  { code: '94', name: 'Sri Lanka' },
  { code: '212', name: 'Morocco' },
  { code: '213', name: 'Algeria' },
  { code: '216', name: 'Tunisia' },
  { code: '218', name: 'Libya' },
  { code: '220', name: 'The Gambia' },
  { code: '221', name: 'Senegal' },
  { code: '222', name: 'Mauritania' },
  { code: '223', name: 'Mali' },
  { code: '224', name: 'Guinea' },
  { code: '225', name: "Côte d'Ivoire" },
  { code: '226', name: 'Burkina Faso' },
  { code: '227', name: 'Niger' },
  { code: '228', name: 'Togo' },
  { code: '229', name: 'Benin' },
  { code: '230', name: 'Mauritius' },
  { code: '231', name: 'Liberia' },
  { code: '232', name: 'Sierra Leone' },
  { code: '233', name: 'Ghana' },
  { code: '234', name: 'Nigeria' },
  { code: '235', name: 'Chad' },
  { code: '236', name: 'Central African Republic' },
  { code: '237', name: 'Cameroon' },
  { code: '238', name: 'Cabo Verde' },
  { code: '240', name: 'Equatorial Guinea' },
  { code: '241', name: 'Gabon' },
  { code: '242', name: 'The Republic of the Congo' },
  { code: '243', name: 'Democratic Republic of the Congo' },
  { code: '244', name: 'Angola' },
  { code: '246', name: 'British Indian Ocean Territory' },
  { code: '248', name: 'Seychelles' },
  { code: '250', name: 'Rwanda' },
  { code: '251', name: 'Ethiopia' },
  { code: '252', name: 'Somalia' },
  { code: '253', name: 'Djibouti' },
  { code: '254', name: 'Kenya' },
  { code: '255', name: 'Tanzania' },
  { code: '256', name: 'Uganda' },
  { code: '257', name: 'Burundi' },
  { code: '258', name: 'Mozambique' },
  { code: '260', name: 'Zambia' },
  { code: '261', name: 'Madagascar' },
  { code: '262', name: 'Mayotte' },
  { code: '263', name: 'Zimbabwe' },
  { code: '264', name: 'Namibia' },
  { code: '265', name: 'Malawi' },
  { code: '266', name: 'Lesotho' },
  { code: '267', name: 'Botswana' },
  { code: '268', name: 'Swaziland' },
  { code: '269', name: 'Comoros' },
  { code: '291', name: 'Eritrea' },
  { code: '297', name: 'Aruba' },
  { code: '298', name: 'Faroe Islands' },
  { code: '299', name: 'Greenland' },
  { code: '350', name: 'Gibraltar' },
  { code: '351', name: 'Portugal' },
  { code: '352', name: 'Luxembourg' },
  { code: '353', name: 'Ireland' },
  { code: '354', name: 'Iceland' },
  { code: '355', name: 'Albania' },
  { code: '356', name: 'Malta' },
  { code: '357', name: 'Cyprus' },
  { code: '358', name: 'Finland' },
  { code: '359', name: 'Bulgaria' },
  { code: '370', name: 'Lithuania' },
  { code: '371', name: 'Latvia' },
  { code: '372', name: 'Estonia' },
  { code: '373', name: 'Moldova' },
  { code: '374', name: 'Armenia' },
  { code: '375', name: 'Belarus' },
  { code: '376', name: 'Andorra' },
  { code: '377', name: 'Monaco' },
  { code: '378', name: 'San Marino' },
  { code: '379', name: 'Vatican City' },
  { code: '380', name: 'Ukraine' },
  { code: '381', name: 'Serbia' },
  { code: '382', name: 'Montenegro' },
  { code: '385', name: 'Croatia' },
  { code: '386', name: 'Slovenia' },
  { code: '387', name: 'Bosnia and Herzegovina' },
  { code: '389', name: 'Macedonian' },
  { code: '420', name: 'Czech Republic' },
  { code: '421', name: 'Slovakia' },
  { code: '423', name: 'Liechtenstein' },
  { code: '500', name: 'Falkland Islands' },
  { code: '501', name: 'Belize' },
  { code: '503', name: 'El Salvador' },
  { code: '504', name: 'Honduras' },
  { code: '505', name: 'Nicaragua' },
  { code: '506', name: 'Costa Rica' },
  { code: '507', name: 'Panama' },
  { code: '508', name: 'Saint Pierre and Miquelon' },
  { code: '509', name: 'Haiti' },
  { code: '590', name: 'Saint Martin' },
  { code: '592', name: 'Guyana' },
  { code: '594', name: 'French Guiana' },
  { code: '596', name: 'Martinique' },
  { code: '672', name: 'Norfolk Island' },
  { code: '676', name: 'Tonga' },
  { code: '679', name: 'Fiji' },
  { code: '680', name: 'Palau' },
  { code: '681', name: 'Wallis and Futuna' },
  { code: '687', name: 'New Caledonia' },
  { code: '688', name: 'Tuvalu' },
  { code: '689', name: 'French Polynesia' },
  { code: '691', name: 'Federated States of Micronesia' },
  { code: '692', name: 'Marshall Islands' },
  { code: '880', name: 'Bangladesh' },
  { code: '960', name: 'Maldives' },
  { code: '961', name: 'Lebanon' },
  { code: '962', name: 'Jordan' },
  { code: '964', name: 'Iraq' },
  { code: '965', name: 'Kuwait' },
  { code: '966', name: 'Saudi Arabia' },
  { code: '967', name: 'Yemen' },
  { code: '968', name: 'Oman' },
  { code: '971', name: 'United Arab Emirates' },
  { code: '972', name: 'Israel' },
  { code: '973', name: 'Bahrain' },
  { code: '974', name: 'Qatar' },
  { code: '975', name: 'Bhutan' },
  { code: '976', name: 'Mongolia' },
  { code: '977', name: 'Nepal' },
  { code: '992', name: 'Tajikistan' },
  { code: '993', name: 'Turkmenistan' },
  { code: '994', name: 'Azerbaijan' },
  { code: '995', name: 'Georgia' },
  { code: '996', name: 'Kyrgyzstan' },
  { code: '998', name: 'Uzbekistan' },
  { code: '1242', name: 'Bahamas' },
  { code: '1246', name: 'Barbados' },
  { code: '1264', name: 'Anguilla' },
  { code: '1268', name: 'Antigua and Barbuda' },
  { code: '1284', name: 'British Virgin Islands' },
  { code: '1345', name: 'Cayman Islands' },
  { code: '1441', name: 'Bermuda' },
  { code: '1473', name: 'Grenada' },
  { code: '1649', name: 'Turks and Caicos Islands' },
  { code: '1664', name: 'Montserrat' },
  { code: '1721', name: 'Sint Maarten' },
  { code: '1758', name: 'Saint Lucia' },
  { code: '1767', name: 'Dominica' },
  { code: '1784', name: 'Saint Vincent and the Grenadines' },
  { code: '1868', name: 'Trinidad and Tobago' },
  { code: '1869', name: 'Saint Kitts and Nevis' },
  { code: '1876', name: 'Jamaica' },
  { code: '4779', name: 'Svalbard and Jan Mayen' },
];

/** Tên nước theo code — fallback chính code khi không có trong bảng. */
export function countryName(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.name ?? code;
}
